/*
    Copyright (C) 2001 by Christian Taubenheim <mail at xp-antispy.org>
    This file is part of xp-AntiSpy http://www.xp-AntiSpy.org.

    xp-AntiSpy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    xp-AntiSpy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with xp-AntiSpy. If not, see <http://www.gnu.org/licenses/
*/
/*
    Do not touch. This file is automatically generated from ../templates/settings_helper.tpl
    Make changes to the template file instead.
*/

#if !defined(_SETTINGS_HEADER_)
#define _SETTINGS_HEADER_
#include "GlobalConstants.h"

const int getGroup(int settingId)
{
	switch(settingId)
	{
		case IDS_FIREWALL:
		case IDS_HIDE_IN_NETWORK:
		case IDS_RESTRICTANONYMOUS:
		case IDS_NONETCRAWL:
		case IDS_NO_WGA_CHECK:
		case IDS_NET_NO_RECENT_DOCS:
			return GI_NETWORK;
		case IDS_IE_SCHEDULED_UPDATES:
		case IDS_IE_CHECK_4_UPDATES:
		case IDS_IE_INTEGRATED_AUTHENTICATION:
		case IDS_MAX_CONNECTIONS:
		case IDS_IE_FORM_SUGGEST:
		case IDS_IE_UPLDDRVINFO:
		case IDS_IE_JAVASCRIPT:
		case IDS_IE_ACTIVEX:
		case IDS_IE_POPUP_BLOCKER:
		case IDS_IE_WATSON:
		case IDS_IE_CLEAN_CACHE:
		case IDS_DO_NOT_ALLOW_IE70:
		case IDS_IE_PHISHING_FILTER:
		case IDS_IE_NO_SQM:
		case IDS_IE_SUGGESTED_SITES:
		case IDS_CERT_REVOCATION:
		case IDS_CERT_TRUST:
		case IDS_NO_HTTPS_CACHE:
			return GI_INTERNET_EXPLORER;
		case IDS_MEDIAPLAYER_LICENSES:
		case IDS_MEDIAPLAYER_SEND_GUID:
		case IDS_MEDIAPLAYER_CODECS:
		case IDS_MP9_ADDMEDIATOLIB:
		case IDS_MP9_RETRIEVEMETADATA:
		case IDS_MP9_USAGETRACKING:
		case IDS_MP9_SAVEMRU:
		case IDS_MEDIAPLAYER_UPDATE:
		case IDS_MP_START_IN_MEDIA_GUIDE:
		case IDS_MEDIAPLAYER_BLOCKUNINSTALL:
		case IDS_WMP_PREVENT_LIBRARY_SHARING:
			return GI_MEDIAPLAYER;
		case IDS_MESSENGER_AUTOSTART:
		case IDS_MESSENGER_DEINSTALL:
			return GI_MESSENGER;
		case IDS_SERVICES_ERROR_REPORTS:
		case IDS_SERVICES_AUTO_UPDATES:
		case IDS_SERVICES_TIMESERVER:
		case IDS_SERVICES_TASKSCHEDULER:
		case IDS_SERVICES_UPNP:
		case IDS_SERVICES_MSGSRV:
		case IDS_SERVICES_FIREWALL:
		case IDS_SERVICES_SEC_CTR:
		case IDS_SERVICES_RPCLOCATOR:
		case IDS_SERVICES_INDEXER:
		case IDS_SERVICES_WINDOWS_DEFENDER:
			return GI_SERVICES;
		case IDS_REGSVR_REGWIZC:
		case IDS_REGSVR_LICDLL:
			return GI_REGSVR;
		case IDS_TWEAK_COMMAND_HERE:
		case IDS_TWEAK_SVC_WmdmPmSN:
		case IDS_TWEAK_SVC_SUPPORT_CTR:
		case IDS_TWEAK_DEL_CTFMON:
		case IDS_TWEAK_CLEANUP_WIZ:
		case IDS_TWEAK_WINUPDATE_NO_DRIVER:
		case IDS_TWEAK_WEBSERVICE:
		case IDS_TWEAK_BSOD_AUTOREBOOT:
		case IDS_TWEAK_DEV_MANAGER:
		case IDS_TWEAK_NO_WINTOUR:
		case IDS_NO_THUMBNAIL_CACHE:
		case IDS_NO_SEARCH_ASSISTANT:
		case IDS_DISABLE_UAC:
		case IDS_NO_UNREAD_MAIL:
		case IDS_NO_TEREDO:
		case IDS_NO_ISATAP:
		case IDS_NO_NCSI:
		case IDS_NO_ROOT_CERT:
		case IDS_NO_FORCEREBOOT:
		case IDS_TWEAK_NO_SHORTCUT_ARROW:
		case IDS_NO_RECENT_DOCS:
		case IDS_TWEAK_SVC_BITS:
			return GI_TWEAKS;
		case IDS_ALEXA:
		case IDS_SUPPORTUSER:
		case IDS_REMOTEDESKTOP:
		case IDS_REGDONE:
		case IDS_TIME_SYNC:
		case IDS_BALLOON_TIPS:
		case IDS_CLEAR_PAGEFILE:
		case IDS_OE_START_MESSENGER:
		case IDS_FAST_SHUTDOWN:
		case IDS_REGSVR_ZIPFLDR:
		case IDS_SHOW_FILE_EXT:
		case IDS_DENY_REGEDIT:
		case IDS_SCRIPTING_HOST:
		case IDS_SHOW_LAST_USERNAME:
		case IDS_LNK_SUFFIX:
		case IDS_PIF_SUFFIX:
		case IDS_SHC_SUFFIX:
		case IDS_URL_SUFFIX:
		case IDS_SHB_SUFFIX:
		case IDS_CD_AUTORUN:
		case IDS_CLEAN_RECENT_DOCS:
		case IDS_DONT_REPORT_INFECTION:
		case IDS_NOLMHASH:
		case IDS_READER_DISABLE_JS:
		case IDS_NO_VDM:
			return GI_MISCELLANOUS;
		case IDS_ERROR_REPORTS_SEND:
		case IDS_OXP_ERRORREPORT:
			return GI_ERROR_REPORTS;

	}
	return -1;
}

#endif // _SETTINGS_HEADER_
